# Generated by Django 3.2.15 on 2022-10-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_rexhwh', upload_to='images/'),
        ),
    ]
